/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package ui;

/**
 *
 * @author Sebas
 */
package Calculadora;
import javax.swing.ImageIcon;
/**
 *
 * @author sb
 */
public class VentanaPrincipal extends javax.swing.JFrame {
  private boolean startNewNumber = true;
  private double firstNumber = 0; // Almacena el primer num para la operación
  private String currentOperator = ""; // Indica el operador actual +, -, *, /
  private boolean decimalAdded = false; // Controla si ya se agregó un punto decimal al numero
  private double memory = 0; // Variable para guardar numeros en memoria
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
        jLabel1.setText("0");
  //Configuracion de hotkeys
    // MC (CTRL+L)
    background.getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW).put(
        javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK), "memoryClear");
    background.getActionMap().put("memoryClear", new javax.swing.AbstractAction() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            memoryClear();
        }
    });
    // MR (CTRL+R)
    background.getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW).put(
        javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK), "memoryRecall");
    background.getActionMap().put("memoryRecall", new javax.swing.AbstractAction() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            memoryRecall();
        }
    });
    // MS (CTRL+M)
    background.getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW).put(
        javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK), "memoryStore");
    background.getActionMap().put("memoryStore", new javax.swing.AbstractAction() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            memoryStore();
        }
    });
    // M+ (CTRL+P)
    background.getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW).put(
        javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK), "memoryAdd");
    background.getActionMap().put("memoryAdd", new javax.swing.AbstractAction() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            memoryAdd();
        }
    });

    // M- (CTRL+Q)
    background.getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW).put(
        javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK), "memorySubtract");
    background.getActionMap().put("memorySubtract", new javax.swing.AbstractAction() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            memorySubtract();
        }
    });
    // CE (SUPRIM)
    background.getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW).put(
        javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0), "clearEntry"); 
    background.getActionMap().put("clearEntry", new javax.swing.AbstractAction() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            clearEntry();
        }
    });
    // C (ESC)
    background.getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW).put(
        javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0), "clearAll"); 
    background.getActionMap().put("clearAll", new javax.swing.AbstractAction() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            clearButtonActionPerformed(e);
        }
    });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora Windows");

        background.setBackground(new java.awt.Color(51, 51, 51));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 49, 360, 140));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        background.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 56, 54));

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        background.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 56, 54));

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        background.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 56, 54));

        jButton4.setBackground(new java.awt.Color(0, 102, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        background.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 56, 54));

        jButton5.setBackground(new java.awt.Color(0, 102, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        background.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 56, 54));

        jButton6.setBackground(new java.awt.Color(0, 102, 102));
        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        background.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 56, 54));

        jButton7.setBackground(new java.awt.Color(0, 102, 102));
        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        background.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 56, 54));

        jButton8.setBackground(new java.awt.Color(0, 102, 102));
        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        background.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 56, 54));

        jButton9.setBackground(new java.awt.Color(0, 102, 102));
        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        background.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 56, 54));

        jButton10.setBackground(new java.awt.Color(0, 102, 102));
        jButton10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("0");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        background.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 56, 70));

        jButton11.setBackground(new java.awt.Color(0, 102, 102));
        jButton11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText(".");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        background.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 56, 70));

        jButton12.setBackground(new java.awt.Color(0, 102, 102));
        jButton12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("+");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        background.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 56, 54));

        jButton13.setBackground(new java.awt.Color(0, 102, 102));
        jButton13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("-");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        background.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 56, 54));

        jButton14.setBackground(new java.awt.Color(0, 102, 102));
        jButton14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("*");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        background.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 56, 54));

        jButton15.setBackground(new java.awt.Color(0, 102, 102));
        jButton15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("/");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        background.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 56, 70));

        jButton16.setBackground(new java.awt.Color(0, 102, 102));
        jButton16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("Del");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        background.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 56, 70));

        jButton17.setBackground(new java.awt.Color(51, 204, 255));
        jButton17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton17.setText("=");
        jButton17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        background.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 120, 190));

        jButton18.setBackground(new java.awt.Color(0, 102, 102));
        jButton18.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("C");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        background.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 120, 54));

        jButton19.setBackground(new java.awt.Color(102, 102, 102));
        jButton19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("MC");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        background.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 80, -1));

        jButton20.setBackground(new java.awt.Color(102, 102, 102));
        jButton20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setText("MR");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        background.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 80, -1));

        jButton21.setBackground(new java.awt.Color(102, 102, 102));
        jButton21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("MS");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        background.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 80, -1));

        jButton22.setBackground(new java.awt.Color(102, 102, 102));
        jButton22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("M+");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        background.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 80, -1));

        jButton23.setBackground(new java.awt.Color(102, 102, 102));
        jButton23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton23.setForeground(new java.awt.Color(255, 255, 255));
        jButton23.setText("M-");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        background.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 80, -1));

        jButton24.setBackground(new java.awt.Color(102, 102, 102));
        jButton24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton24.setForeground(new java.awt.Color(255, 255, 255));
        jButton24.setText("CE");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        background.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 80, -1));

        jButton25.setBackground(new java.awt.Color(102, 102, 102));
        jButton25.setForeground(new java.awt.Color(255, 255, 255));
        jButton25.setText("MOD");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        background.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 90, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Logica de los botones
    // Metodo auxiliar para formatear el resultadoevita == evita.0 para enteros
    private String formatResult(double result) {
        if (result == (long) result) {
            return String.format("%d", (long) result);
        } else {
            return String.format("%s", result);
    }
}
    private void numberButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String buttonText = ((javax.swing.JButton)evt.getSource()).getText();
        String currentDisplay = jLabel1.getText();
        // Muestra numero en el label
        if (startNewNumber || currentDisplay.equals("0")) {
            jLabel1.setText(buttonText);
            startNewNumber = false; 
        } else {
            // Si ya hay numeros añade el nuevo numero al final
            // Limita la cantidad de caracteres en el label a 10
            if (currentDisplay.length() < 10) { // Limite de 10
                jLabel1.setText(currentDisplay + buttonText);
            }
        }
    }
//
private void performCalculation() {
    double secondNumber = Double.parseDouble(jLabel1.getText());
    double result = 0;
    switch (currentOperator) {
        case "+":
            result = firstNumber + secondNumber;
            break;
        case "-":
            result = firstNumber - secondNumber;
            break;
        case "*":
            result = firstNumber * secondNumber;
            break;
        case "/":
            if (secondNumber != 0) {
                result = firstNumber / secondNumber;
            } else {
                jLabel1.setText("Error");
                firstNumber = 0;
                currentOperator = "";
                startNewNumber = true;
                decimalAdded = false;
                return;
            }
            break;
        case "MOD":
            if (secondNumber != 0) {
                result = firstNumber % secondNumber;
            } else {
                jLabel1.setText("Error");
                firstNumber = 0;
                currentOperator = "";
                startNewNumber = true;
                decimalAdded = false;
                return;
            }
            break;
    }
//Muestra resultado en el label
    jLabel1.setText(formatResult(result));
    firstNumber = result;
}
   // 
    private void decimalButtonActionPerformed(java.awt.event.ActionEvent evt) {
       String currentDisplay = jLabel1.getText();
        if (!currentDisplay.contains(".")) {
            if (startNewNumber) {
                jLabel1.setText("0.");
                startNewNumber = false;
            } else {
                jLabel1.setText(currentDisplay + ".");
            }
            startNewNumber = false;
            decimalAdded = true; // Hace saber que ya se agregó un decimal
        }
    }
//
    private void backspaceButtonActionPerformed(java.awt.event.ActionEvent evt) {
      String currentDisplay = jLabel1.getText();
        if (currentDisplay.length() > 1) {
            // Si hay mas de un caracter elimina el ultimo
            jLabel1.setText(currentDisplay.substring(0, currentDisplay.length() - 1));
        } else {
            jLabel1.setText("0");
            startNewNumber = true; 
        }
    }
//
    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {
        jLabel1.setText("0"); // Restablece la pantalla a 0
        startNewNumber = true; //prepara la pantalla para un nuevo numero
        firstNumber = 0;       // Reinicia el primer num
        currentOperator = "";  // Reinicia el operador
        decimalAdded = false;  // Reinicia decimal
    }
//
    private void operationButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Si ya hay un operador y no estamos empezando un nuevo número, significa que es una operación encadenada
    if (!currentOperator.isEmpty() && !startNewNumber) {
        // Ejecuta la operación anterior antes de guardar la nueva
        performCalculation(); // Llamamos a una nueva función para el cálculo
    }
    firstNumber = Double.parseDouble(jLabel1.getText());
    currentOperator = ((javax.swing.JButton)evt.getSource()).getText();
    startNewNumber = true;
    decimalAdded = false; 
    }
    //
    private void equalsButtonActionPerformed(java.awt.event.ActionEvent evt) {
    if (!currentOperator.isEmpty()) {
        performCalculation(); 
        currentOperator = ""; // Resetea el operadordespués de la operación
    }
    startNewNumber = true; //Despues de dar un resultado se limpia memoria
    decimalAdded = false; 
}
    // MC Memory Clear Elimina cualquier número almacenado en memoria.
private void memoryClear() {
    memory = 0;
}

// MR (Memory Recall): Recupera el número almacenado en memoria y lo muestra. El número permanece en memoria.
private void memoryRecall() {
    jLabel1.setText(formatResult(memory)); // Muestra el número de la memoria en la pantalla
    startNewNumber = true; // El próximo número ingresado comenzará de nuevo
    decimalAdded = (memory % 1 != 0); // Ajusta la bandera decimal si el número de memoria tiene decimales
}
// MS (Memory Storage): Almacena en memoria el número mostrado.
private void memoryStore() {
    memory = Double.parseDouble(jLabel1.getText()); // Almacena el número actual en la pantalla
}
// M+: Suma el número mostrado a otro número que se encuentre en memoria.
private void memoryAdd() {
    memory += Double.parseDouble(jLabel1.getText());

}
// M-: Resta el número mostrado a otro número que se encuentre en memoria.
private void memorySubtract() {
    memory -= Double.parseDouble(jLabel1.getText());
}
//CE clear Entry Elimina el numero  mostrado
// Se utiliza para cuando se comete un error en el ingreso de datos pero sin eliminar el calculo
private void clearEntry() {
    jLabel1.setText("0"); // Limpia el numero actual en pantalla
    startNewNumber = true; //
    decimalAdded = false; // Reinicia decimal
}      
//
    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
       equalsButtonActionPerformed(evt);      
    }//GEN-LAST:event_jButton17ActionPerformed
//
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        numberButtonActionPerformed(evt);      
    }//GEN-LAST:event_jButton3ActionPerformed
//
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    numberButtonActionPerformed(evt);    }//GEN-LAST:event_jButton1ActionPerformed
//
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        numberButtonActionPerformed(evt);      
    }//GEN-LAST:event_jButton2ActionPerformed
//
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        numberButtonActionPerformed(evt);      
    }//GEN-LAST:event_jButton4ActionPerformed
//
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        numberButtonActionPerformed(evt);      
    }//GEN-LAST:event_jButton5ActionPerformed
//
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        numberButtonActionPerformed(evt);      
    }//GEN-LAST:event_jButton6ActionPerformed
//
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        numberButtonActionPerformed(evt);      
    }//GEN-LAST:event_jButton7ActionPerformed
//
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        numberButtonActionPerformed(evt);      
    }//GEN-LAST:event_jButton8ActionPerformed
//
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        numberButtonActionPerformed(evt);      
    }//GEN-LAST:event_jButton9ActionPerformed
//
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        numberButtonActionPerformed(evt);      
    }//GEN-LAST:event_jButton10ActionPerformed
//
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        decimalButtonActionPerformed(evt);
    }//GEN-LAST:event_jButton11ActionPerformed
//
    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        backspaceButtonActionPerformed(evt);      
    }//GEN-LAST:event_jButton16ActionPerformed
//
    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        operationButtonActionPerformed(evt); 
    }//GEN-LAST:event_jButton15ActionPerformed
//
    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        operationButtonActionPerformed(evt); 
    }//GEN-LAST:event_jButton14ActionPerformed
//
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        operationButtonActionPerformed(evt); 
    }//GEN-LAST:event_jButton13ActionPerformed
//
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        operationButtonActionPerformed(evt);
    }//GEN-LAST:event_jButton12ActionPerformed
//
    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        clearButtonActionPerformed(evt);      
    }//GEN-LAST:event_jButton18ActionPerformed
//
    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        memoryClear();
    }//GEN-LAST:event_jButton19ActionPerformed
//
    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        memoryRecall();
    }//GEN-LAST:event_jButton20ActionPerformed
//
    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        memoryStore();
    }//GEN-LAST:event_jButton21ActionPerformed
//
    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        memoryAdd();
    }//GEN-LAST:event_jButton22ActionPerformed
//
    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        memorySubtract();
    }//GEN-LAST:event_jButton23ActionPerformed
//
    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        clearEntry();
    }//GEN-LAST:event_jButton24ActionPerformed
//
    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        operationButtonActionPerformed(evt);
    }//GEN-LAST:event_jButton25ActionPerformed
//
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}

