package ui;
import dominio.Producto;
import dominio.Usuario; 
import servicio.ProductoServicio;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDateTime; // Importación necesaria para manejar LocalDateTime
;

/**
 *
 * @author Sebas
 */
public class VentanaPrincipal extends javax.swing.JFrame {
        private ProductoServicio productoServicio;
        private Usuario usuarioLogueado; // Para almacenar el objeto Usuario completo

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(Usuario usuario) {
        initComponents();
        setLocationRelativeTo(null);
        this.usuarioLogueado = usuario; 
        this.productoServicio = new ProductoServicio();
        cargarProductosEnTabla();
    }
    
    private void cargarProductosEnTabla() {
        try {
            List<Producto> productos = productoServicio.listarTodos(); // Usa listarTodos()
            DefaultTableModel model = (DefaultTableModel) tblProductos.getModel();
            model.setRowCount(0); // Limpiar la tabla
            
            // Asignar nombres a las columnas
            model.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Precio", "Activo", "Stock"}); 
            for (Producto producto : productos) {
                model.addRow(new Object[]{
                    producto.getId(),
                    producto.getNombre(),
                    producto.getPrecio(),
                    producto.isActivo(), 
                    producto.getStock() 
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los productos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Busca productos por nombre y actualiza la tabla con los resultados.
     * @param nombre El nombre del producto a buscar.
     */
    private void buscarProductosPorNombre(String nombre) {
        try {
            // Se asume que ProductoServicio tendrá un método para buscar por nombre
            List<Producto> productos = productoServicio.buscarPorNombre(nombre); 
            DefaultTableModel model = (DefaultTableModel) tblProductos.getModel();
            model.setRowCount(0); // Limpiar la tabla
            
            for (Producto producto : productos) {
                model.addRow(new Object[]{
                    producto.getId(),
                    producto.getNombre(),
                    producto.getPrecio(),
                    producto.isActivo(),
                    producto.getStock()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar productos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); // Para depuración
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        btnBuscarProducto = new javax.swing.JButton();
        jMenuBarGestionarProductos = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuProducto = new javax.swing.JMenu();
        jMenuItemGestionarProductos = new javax.swing.JMenuItem();
        jMenuVentas = new javax.swing.JMenu();
        jMenuItemRealizarVenta = new javax.swing.JMenuItem();
        jMenuItemConsultarVenta = new javax.swing.JMenuItem();
        jMenuItemGenerarFactura = new javax.swing.JMenuItem();
        jMenuHerramientas = new javax.swing.JMenu();
        jMenuItemCalculadora = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Cafeteria");

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        jLabel1.setText("Consultar producto según nombre");

        btnBuscarProducto.setText("Buscar");
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });

        jMenuArchivo.setText("Archivo");

        jMenu5.setText("Salir");
        jMenuArchivo.add(jMenu5);

        jMenuBarGestionarProductos.add(jMenuArchivo);

        jMenuProducto.setText("Producto");

        jMenuItemGestionarProductos.setText("Gestionar productos");
        jMenuItemGestionarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionarProductosActionPerformed(evt);
            }
        });
        jMenuProducto.add(jMenuItemGestionarProductos);

        jMenuBarGestionarProductos.add(jMenuProducto);

        jMenuVentas.setText("Ventas");
        jMenuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVentasActionPerformed(evt);
            }
        });

        jMenuItemRealizarVenta.setText("Realizar venta");
        jMenuItemRealizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRealizarVentaActionPerformed(evt);
            }
        });
        jMenuVentas.add(jMenuItemRealizarVenta);

        jMenuItemConsultarVenta.setText("Consultar ventas");
        jMenuItemConsultarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarVentaActionPerformed(evt);
            }
        });
        jMenuVentas.add(jMenuItemConsultarVenta);

        jMenuItemGenerarFactura.setText("generarfactura");
        jMenuItemGenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGenerarFacturaActionPerformed(evt);
            }
        });
        jMenuVentas.add(jMenuItemGenerarFactura);

        jMenuBarGestionarProductos.add(jMenuVentas);

        jMenuHerramientas.setText("Herramientas");

        jMenuItemCalculadora.setText("Calculadora");
        jMenuItemCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCalculadoraActionPerformed(evt);
            }
        });
        jMenuHerramientas.add(jMenuItemCalculadora);

        jMenuBarGestionarProductos.add(jMenuHerramientas);

        jMenuAyuda.setText("Ayuda");

        jMenuItem1.setText("Contacto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuItem1);

        jMenuItem2.setText("Acerca de");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuItem2);

        jMenuBarGestionarProductos.add(jMenuAyuda);

        setJMenuBar(jMenuBarGestionarProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarProducto)
                .addContainerGap(204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProducto))
                .addGap(0, 246, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        String nombreABuscar = txtNombreProducto.getText();
        if (nombreABuscar.isEmpty()) {
            cargarProductosEnTabla(); // Si el campo está vacío, muestra todos los productos
        } else {
            buscarProductosPorNombre(nombreABuscar);
        }
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void jMenuItemGestionarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionarProductosActionPerformed
        GestionarProductosUI gestionarProductosUI = new GestionarProductosUI();
        gestionarProductosUI.setVisible(true);
    }//GEN-LAST:event_jMenuItemGestionarProductosActionPerformed

    private void jMenuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuVentasActionPerformed

    private void jMenuItemGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGenerarFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemGenerarFacturaActionPerformed

    private void jMenuItemConsultarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarVentaActionPerformed
        ConsultarVentasUI consultarVentasUI = new ConsultarVentasUI();
        consultarVentasUI.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultarVentaActionPerformed

    private void jMenuItemRealizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRealizarVentaActionPerformed
        RealizarVentaUI realizarVentaUI = new RealizarVentaUI();
        realizarVentaUI.setVisible(true);
    }//GEN-LAST:event_jMenuItemRealizarVentaActionPerformed

    private void jMenuItemCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCalculadoraActionPerformed
        CalculadoraUI calculadoraUI = new CalculadoraUI();
        calculadoraUI.setVisible(true);
    }//GEN-LAST:event_jMenuItemCalculadoraActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(this, "Para soporte, contacta a sebas01benavides@gmail.com",
                 "Contacto",
                 JOptionPane.INFORMATION_MESSAGE);    
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JOptionPane.showMessageDialog(this, "Sistema caja para cafeteria univertisaria. Realizado por Sebastián Benavides",
                 "Acerca de",
                 JOptionPane.INFORMATION_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBarGestionarProductos;
    private javax.swing.JMenu jMenuHerramientas;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemCalculadora;
    private javax.swing.JMenuItem jMenuItemConsultarVenta;
    private javax.swing.JMenuItem jMenuItemGenerarFactura;
    private javax.swing.JMenuItem jMenuItemGestionarProductos;
    private javax.swing.JMenuItem jMenuItemRealizarVenta;
    private javax.swing.JMenu jMenuProducto;
    private javax.swing.JMenu jMenuVentas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtNombreProducto;
    // End of variables declaration//GEN-END:variables
}
